version: 0.2

phases:
  install:
    commands:
      - echo Installing latest version of node...
      - npm i npm@latest -g
  pre_build:
    commands:
      - echo Installing project dependencies...
      - npm install
      - echo Fixing any dependencies requiring a security update...
      - npm audit fix
  build:
    commands:
      - echo Running the build...
      - npm run build
  post_build:
    commands:
      - echo Syncing new files to S3...
      - aws s3 sync ./build $S3_BUCKET --cache-control max-age=3600
      - echo Sync complete and new site deployed!
