version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    type: zip
    paths:
      - './build/**/*'
  cache:
    paths:
      - './node_modules/**/*'
